### ISSUE TITLE
nitime.viz import error, ImportError: 'No module named mpl_toolkits.axes_grid'

### ISSUE THREAD

**Issue by apiszcz** [nipy/nitime#129]
I'm having an import issue, looking closer at mpl_toolkits\axes_grid\__init__.py
indicates something may have changed with the import for make_axes_locatable

1. Versions
Python 2.7
matplotlib 1.4.3
nitime 0.5

import nitime.viz
FILE: mpl_toolkits\axes_grid\__init__.py\
from .axes_divider import Divider, SubplotDivider, LocatableAxes, \
     make_axes_locatable
from .axes_grid import Grid, ImageGrid, AxesGrid
#from axes_divider import make_axes_locatable

= ERROR
lib\matplotlib\cbook.py:137: MatplotlibDeprecationWarning: The matplotlib.mpl module was deprecated in version 1.3. Use `import matplotlib as mpl` instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
ImportError: 'No module named mpl_toolkits.axes_grid'

**Comment by apiszcz** [comment]
I added an empty  __init__.py to the mpl_toolkits folder and issue appears to be resolved..

**Comment by arokem** [comment]
I could not replicate the original error, but fwiw, I have at least
modernized the import of mpl to address that deprecation warning:

https://github.com/nipy/nitime/pull/130

Thanks for reporting!

**Comment by arokem** [comment]
Fixed through #130
