### ISSUE TITLE
Multi-taper coherence estimation with two signals of different length?

### ISSUE THREAD

**Issue by apiszcz** [nipy/nitime#131]
Is there a common method for using Multi-taper coherence estimation with signals of different lengths? Let's say I have signal1 S1, and signal2 S2, and S2 is 0.1% of the length of S2. Is it possible / practical to use Multi-taper coherence estimation in this situation to see if S2 is similar to subsection of s1.
Thank you.

**Comment by arokem** [comment]
I think that you would want to make sure that the bandwidth ends up the
same in both time-series. But I don't have experience with this kind of
thing. There might be some wisdom related to this in one of David Thomson's
papers. This one, for example:
http://www.sciencemag.org/content/268/5207/59.short, in which it seems that
time-series with different lengths are being cohered against each other.

Another good place to ask about this is at the stats stackexchange site:
http://stats.stackexchange.com/, and also neurostars:
https://neurostars.org/

Sorry to not be more helpful... Please do report back if you find any
definitive answer to this!

**Comment by apiszcz** [comment]
The approach was to segment the larger signal into a reasonable sample size (512), and use each segment as a channel. I padded out the last channel with values of 0 if less than 512.. Next I concatenated S2 and 0 padded the remainder of that last segment. The result was similar to the tutorial for the multi taper coherence estimation.

**Comment by arokem** [comment]
Yes - that sounds like a very good approach. Thanks so much for reporting back! I'll go ahead and close the issue
