### ISSUE TITLE
nodes contour missing in drawmatrix_channels

### ISSUE THREAD

**Issue by grjd** [nipy/nitime#153]
hi,
Plotting this but the nodes are not plot, why is this?

drawgraph_channels(corr_matrix, label_map,title=msgtitle)

(Pdb) corr_matrix 
[[ 1.        ,  0.67542034,  0.55833702,  0.64782126],
       [ 0.67542034,  1.        ,  0.73439529,  0.49988066],
       [ 0.55833702,  0.73439529,  1.        ,  0.44339273],
       [ 0.64782126,  0.49988066,  0.44339273,  1.        ]])
(Pdb) label_map
['Post. Cing. Cortex', 'Left Tmp.Ptl. junction', 'Right Tmp.Ptl. junction', 'Medial PFC ']
![figure_33](https://user-images.githubusercontent.com/7142903/31349936-781c6180-ad25-11e7-984a-0459ec738f94.png)

**Comment by arokem** [comment]
Sorry for my slowness here. I can confirm that I see this issue on my machine as well.

**Comment by arokem** [comment]
Looks like the call out to networkx needs to change. For reference: 

https://networkx.github.io/documentation/networkx-1.9/examples/drawing/labels_and_colors.html

**Comment by arokem** [comment]
OK - there's a fix in #157. Should get into master soon.
