### ISSUE TITLE
Error when Installing

### ISSUE THREAD

**Issue by adumudaliar** [nipy/nitime#162]
Hello,
I made a copy of the git respository and used the python setup.py install command ( running the command in the folder installed).

I get the following error:

\nitime-master\nitime-master>python setup.py install
C:\Anaconda\lib\site-packages\setuptools\dist.py:355: UserWarning: Normalizing '
0.8.dev' to '0.8.dev0'
  normalized_version,
running install
running bdist_egg
running egg_info
creating nitime.egg-info
writing nitime.egg-info\PKG-INFO
writing dependency_links to nitime.egg-info\dependency_links.txt
writing requirements to nitime.egg-info\requires.txt
writing top-level names to nitime.egg-info\top_level.txt
writing manifest file 'nitime.egg-info\SOURCES.txt'
reading manifest file 'nitime.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'doc\_build'
no previously-included directories found matching 'doc\api\generated'
warning: no previously-included files matching '*~' found anywhere in distributi
on
warning: no previously-included files matching '*.flc' found anywhere in distrib
ution
warning: no previously-included files matching '*.pyc' found anywhere in distrib
ution
warning: no previously-included files matching '.dircopy.log' found anywhere in
distribution
warning: no previously-included files matching '.git' found anywhere in distribu
tion
writing manifest file 'nitime.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.6
creating build\lib.win-amd64-3.6\nitime
copying nitime\descriptors.py -> build\lib.win-amd64-3.6\nitime
copying nitime\index_utils.py -> build\lib.win-amd64-3.6\nitime
copying nitime\lazy.py -> build\lib.win-amd64-3.6\nitime
copying nitime\lazyimports.py -> build\lib.win-amd64-3.6\nitime
copying nitime\six.py -> build\lib.win-amd64-3.6\nitime
copying nitime\timeseries.py -> build\lib.win-amd64-3.6\nitime
copying nitime\utils.py -> build\lib.win-amd64-3.6\nitime
copying nitime\version.py -> build\lib.win-amd64-3.6\nitime
copying nitime\viz.py -> build\lib.win-amd64-3.6\nitime
copying nitime\_mpl_units.py -> build\lib.win-amd64-3.6\nitime
copying nitime\__init__.py -> build\lib.win-amd64-3.6\nitime
creating build\lib.win-amd64-3.6\nitime\algorithms
copying nitime\algorithms\autoregressive.py -> build\lib.win-amd64-3.6\nitime\al
gorithms
copying nitime\algorithms\cohere.py -> build\lib.win-amd64-3.6\nitime\algorithms

copying nitime\algorithms\correlation.py -> build\lib.win-amd64-3.6\nitime\algor
ithms
copying nitime\algorithms\entropy.py -> build\lib.win-amd64-3.6\nitime\algorithm
s
copying nitime\algorithms\event_related.py -> build\lib.win-amd64-3.6\nitime\alg
orithms
copying nitime\algorithms\filter.py -> build\lib.win-amd64-3.6\nitime\algorithms

copying nitime\algorithms\spectral.py -> build\lib.win-amd64-3.6\nitime\algorith
ms
copying nitime\algorithms\wavelet.py -> build\lib.win-amd64-3.6\nitime\algorithm
s
copying nitime\algorithms\__init__.py -> build\lib.win-amd64-3.6\nitime\algorith
ms
creating build\lib.win-amd64-3.6\nitime\analysis
copying nitime\analysis\base.py -> build\lib.win-amd64-3.6\nitime\analysis
copying nitime\analysis\coherence.py -> build\lib.win-amd64-3.6\nitime\analysis
copying nitime\analysis\correlation.py -> build\lib.win-amd64-3.6\nitime\analysi
s
copying nitime\analysis\event_related.py -> build\lib.win-amd64-3.6\nitime\analy
sis
copying nitime\analysis\granger.py -> build\lib.win-amd64-3.6\nitime\analysis
copying nitime\analysis\normalization.py -> build\lib.win-amd64-3.6\nitime\analy
sis
copying nitime\analysis\snr.py -> build\lib.win-amd64-3.6\nitime\analysis
copying nitime\analysis\spectral.py -> build\lib.win-amd64-3.6\nitime\analysis
copying nitime\analysis\__init__.py -> build\lib.win-amd64-3.6\nitime\analysis
creating build\lib.win-amd64-3.6\nitime\fmri
copying nitime\fmri\hrf.py -> build\lib.win-amd64-3.6\nitime\fmri
copying nitime\fmri\io.py -> build\lib.win-amd64-3.6\nitime\fmri
copying nitime\fmri\__init__.py -> build\lib.win-amd64-3.6\nitime\fmri
creating build\lib.win-amd64-3.6\nitime\tests
copying nitime\tests\test_algorithms.py -> build\lib.win-amd64-3.6\nitime\tests
copying nitime\tests\test_analysis.py -> build\lib.win-amd64-3.6\nitime\tests
copying nitime\tests\test_descriptors.py -> build\lib.win-amd64-3.6\nitime\tests

copying nitime\tests\test_lazy.py -> build\lib.win-amd64-3.6\nitime\tests
copying nitime\tests\test_timeseries.py -> build\lib.win-amd64-3.6\nitime\tests
copying nitime\tests\test_utils.py -> build\lib.win-amd64-3.6\nitime\tests
copying nitime\tests\test_viz.py -> build\lib.win-amd64-3.6\nitime\tests
copying nitime\tests\__init__.py -> build\lib.win-amd64-3.6\nitime\tests
creating build\lib.win-amd64-3.6\nitime\algorithms\tests
copying nitime\algorithms\tests\test_autoregressive.py -> build\lib.win-amd64-3.
6\nitime\algorithms\tests
copying nitime\algorithms\tests\test_coherence.py -> build\lib.win-amd64-3.6\nit
ime\algorithms\tests
copying nitime\algorithms\tests\test_correlation.py -> build\lib.win-amd64-3.6\n
itime\algorithms\tests
copying nitime\algorithms\tests\test_entropy.py -> build\lib.win-amd64-3.6\nitim
e\algorithms\tests
copying nitime\algorithms\tests\test_event_related.py -> build\lib.win-amd64-3.6
\nitime\algorithms\tests
copying nitime\algorithms\tests\test_spectral.py -> build\lib.win-amd64-3.6\niti
me\algorithms\tests
copying nitime\algorithms\tests\__init__.py -> build\lib.win-amd64-3.6\nitime\al
gorithms\tests
creating build\lib.win-amd64-3.6\nitime\analysis\tests
copying nitime\analysis\tests\test_base.py -> build\lib.win-amd64-3.6\nitime\ana
lysis\tests
copying nitime\analysis\tests\test_coherence.py -> build\lib.win-amd64-3.6\nitim
e\analysis\tests
copying nitime\analysis\tests\test_correlation.py -> build\lib.win-amd64-3.6\nit
ime\analysis\tests
copying nitime\analysis\tests\test_granger.py -> build\lib.win-amd64-3.6\nitime\
analysis\tests
copying nitime\analysis\tests\test_snr.py -> build\lib.win-amd64-3.6\nitime\anal
ysis\tests
copying nitime\analysis\tests\__init__.py -> build\lib.win-amd64-3.6\nitime\anal
ysis\tests
creating build\lib.win-amd64-3.6\nitime\fmri\tests
copying nitime\fmri\tests\test_io.py -> build\lib.win-amd64-3.6\nitime\fmri\test
s
copying nitime\fmri\tests\__init__.py -> build\lib.win-amd64-3.6\nitime\fmri\tes
ts
copying nitime\LICENSE -> build\lib.win-amd64-3.6\nitime
copying nitime\tests\cxy_matlab.txt -> build\lib.win-amd64-3.6\nitime\tests
copying nitime\tests\dpss_matlab.txt -> build\lib.win-amd64-3.6\nitime\tests
copying nitime\tests\fxx_matlab.txt -> build\lib.win-amd64-3.6\nitime\tests
copying nitime\tests\tseries12.txt -> build\lib.win-amd64-3.6\nitime\tests
copying nitime\tests\long_dpss_matlab.npy -> build\lib.win-amd64-3.6\nitime\test
s
creating build\lib.win-amd64-3.6\nitime\data
copying nitime\data\fmri1.nii.gz -> build\lib.win-amd64-3.6\nitime\data
copying nitime\data\fmri2.nii.gz -> build\lib.win-amd64-3.6\nitime\data
copying nitime\data\grasshopper_spike_times1.txt -> build\lib.win-amd64-3.6\niti
me\data
copying nitime\data\grasshopper_spike_times2.txt -> build\lib.win-amd64-3.6\niti
me\data
copying nitime\data\grasshopper_stimulus1.txt -> build\lib.win-amd64-3.6\nitime\
data
copying nitime\data\grasshopper_stimulus2.txt -> build\lib.win-amd64-3.6\nitime\
data
copying nitime\data\event_related_fmri.csv -> build\lib.win-amd64-3.6\nitime\dat
a
copying nitime\data\fmri_timeseries.csv -> build\lib.win-amd64-3.6\nitime\data
running build_ext
error: [WinError 2] The system cannot find the file specified

Thanks

**Comment by arokem** [comment]
Assuming that you have Cython installed, if you want to build the software from source,  you will need a compiler (there are some compiled extensions that are part of the software). 

Seeing that you are using Anaconda, if you don't need to install it from source you can get the compiled software with: 

    conda install -c conda-forge nitime

**Comment by arokem** [comment]
I'm going to go ahead and assume this is no longer relevant, but feel free to reopen.
