### ISSUE TITLE
detect_lines is documented incorrectly

### ISSUE THREAD

**Issue by bjarthur** [nipy/nitime#164]
it says that`p` is 1/N.  N is not defined in that docstring.  one might think N is the length of the time series.  but looking at the code, it's actually NFFT.

**Comment by arokem** [comment]
Thanks for your comment! How's [this](https://github.com/nipy/nitime/pull/165)?

**Comment by bjarthur** [comment]
lgtm.  though, would be nice to doc what NFFT defaulted to.  the docstring for `tapered_spectra` doesn't say.

**Comment by arokem** [comment]
Closed through #165
