### ISSUE TITLE
Spike Train Coherence

### ISSUE THREAD

**Issue by ahwillia** [nipy/nitime#167]
I'm trying to compute the coherence between two spike trains (see [Jarvis & Mitra, 2000](http://www.cnbc.cmu.edu/~tai/readings/analysis/JarvisMitra2000.pdf) and http://chronux.org/ for background). I can't tell whether this is supported yet (I don't think it is?) or outside the scope of this project.

More generally, I'm trying to get a sense of whether this package plays well with spike train datasets (e.g. from multielectrode recordings) or is more specialized for analog signals. Any high-level guidance here would be greatly appreciated - thanks!

**Comment by arokem** [comment]
Thanks for reaching out. I'm not 100% sure whether what we have in nitime would already work for you. Would it be sufficient to use a multi-taper cross-spectrum? Section 4 of the paper that you linked seems to suggest this, but I have not read the entire thing. If yes, here is an example of that in nitime: 

http://nipy.org/nitime/examples/multi_taper_coh.html

If this is not sufficient for your needs, I would say that it's not out of scope for nitime, but it is also not on my immediate to-do list (to say it gently), and someone else would have to implement it. I would be willing to review such a contribution, and push out a new release with this, if you decide to implement that.

**Comment by arokem** [comment]
I guess this is not happening 😄
