### ISSUE TITLE
Latest release breaking Python 2.7, 3.4 (SyntaxError)

### ISSUE THREAD

**Issue by effigies** [nipy/nitime#174]
In nipype, tests are breaking in Python 2.7, 3.4, due to the `@` operator:

```
./../../virtualenv/python2.7.15/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
nipype/interfaces/nitime/__init__.py:5: in <module>
    from .analysis import (CoherenceAnalyzerInputSpec, CoherenceAnalyzerOutputSpec,
nipype/interfaces/nitime/analysis.py:28: in <module>
    package_check('nitime')
nipype/utils/misc.py:180: in package_check
    mod = __import__(pkg_name)
../../../virtualenv/python2.7.15/lib/python2.7/site-packages/nitime/__init__.py:26: in <module>
    from . import algorithms
../../../virtualenv/python2.7.15/lib/python2.7/site-packages/nitime/algorithms/__init__.py:62: in <module>
    from nitime.algorithms.event_related import *
E     File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/nitime/algorithms/event_related.py", line 60
E       h = np.array(linalg.pinv(X.T @ X) @ X.T @ y.T)
E                                    ^
E   SyntaxError: invalid syntax
```

**Comment by arokem** [comment]
Argh. Sorry about that. I'll put out a 0.8.1 fixing that. 

What's your plan for kicking Python 2 and 3.4?

**Comment by effigies** [comment]
IDK, @satra?

**Comment by effigies** [comment]
But you can use python_requires in setup.py ([docs](https://setuptools.readthedocs.io/en/latest/setuptools.html)). After a fixed release that will be picked up for 2.7 and 3.4, you can make a new release with `python_requires=">=3.5"` and leave these behind forever.

**Comment by arokem** [comment]
What would that entail for Nipype? Would the nipype testing  simply skip importing nitime  in that case?

**Comment by effigies** [comment]
Nipype tests on 2.7 would only install up to the last release with a compatible `python_requires`. So our tests on 3.5 would use the latest nitime, and our tests on 2.7/3.4 would use nitime 0.8.1.

**Comment by arokem** [comment]
Gotcha. So 0.8.1 followed quickly by a 0.8.2 that reinstates the nice new syntax

**Comment by effigies** [comment]
That works, though just strategically, I would jump to 0.9.0 for the new syntax, to signify a breaking change, and give you room to use 0.8.x to do any remaining fixes for old Python.

**Comment by satra** [comment]
@arokem - i think our alignment for 3.0 was going to be with nibabel. we have not removed 2.7 compatibility layer yet from nipype 1.x. we don't have an explicit date for dropping mostly because we were focused on nipype 2.0. nipype 2.0 is going to be python 3.7+, but things have been a bit slow on that front.

**Comment by arokem** [comment]
This issue should now be fixed in the now-released [0.8.1](https://pypi.org/project/nitime/0.8.1/)

**Comment by effigies** [comment]
Thanks, @arokem.

**Comment by effigies** [comment]
Just to confirm, this fixed the failing nipype tests. Thanks again.
