### ISSUE TITLE
nitime does not work after installed 

### ISSUE THREAD

**Issue by manmanw** [nipy/nitime#177]
Hello,

I have a issue that I cannot use after installed nitime and did not find the setup.py, does this mean not install properly?

I attached errors here .

Thanks in advance if you could help.

Manman

![Screen Shot 2020-04-27 at 5 29 45 PM](https://user-images.githubusercontent.com/8651191/80433801-d48d3d80-88ac-11ea-823d-5b81afbbdf27.png)
![Screen Shot 2020-04-27 at 5 27 47 PM](https://user-images.githubusercontent.com/8651191/80433870-1322f800-88ad-11ea-90eb-85eb51140d9a.png)

**Comment by arokem** [comment]
What steps did you take to install the software?

**Comment by manmanw** [comment]
I used pip install nitime.

even when I use pip list, I can see the nitime.

The same today as when I install "spectrum"

**Comment by arokem** [comment]
I am guessing that this is because your Jupyter notebook is running in a different environment than the one into which you installed the software.
