### ISSUE TITLE
Failing tests with nibabel 3.2.0

### ISSUE THREAD

**Issue by jonringer** [nipy/nitime#181]
Tests fail after bumping to nibabel 3.2.0

```
        npt.assert_(
>           len(f) == 3, 'The wrong number of harmonic components were detected'
            )
E       AssertionError: The wrong number of harmonic components were detected

nitime/tests/test_utils.py:259: AssertionError
```

**Comment by miketrumpis** [comment]
I wrote this stuff back in the day.. don't think it would have anything to
do with nibabel.

I just tried testing it on the master branch and it's ok. Can you paste
your pip freeze or conda list?

(nitime) denali:nitime(master)$ nosetests --pdb -v
nitime/tests/test_utils.py

nitime.tests.test_utils.test_zscore ... ok

nitime.tests.test_utils.test_percent_change ... ok

nitime.tests.test_utils.test_tridi_inverse_iteration ... ok

nitime.tests.test_utils.test_debias ... ok

nitime.tests.test_utils.test_crosscov ... ok

nitime.tests.test_utils.test_autocorr ... ok

Test the implementation of information criteria: ... ok

Testing the multi-intersect utility function ... ok

Test the zero_pad function ... ok

Tests detect_lines utility in the reliable low-SNR scenario. ... ok

Test multi-sequence operation ... ok


----------------------------------------------------------------------

Ran 11 tests in 4.190s


OK

**Comment by jonringer** [comment]
must have been a transient issue. I'm not able to reproduce the error:
```
pytestcachePhase
/nix/store/48m7w39vvblks57bbxlm91gs7hphxsz2-python3.7-nitime-0.8.1
[10:31:38] jon@nixos ~/projects/nixpkgs (master)
$ nix-build -A python37Packages.nibabel
/nix/store/sw5glg2n3xbag5334ih960ijly8qaap3-python3.7-nibabel-3.2.0
[10:32:42] jon@nixos ~/projects/nixpkgs (master)
```

It first appeared in https://github.com/NixOS/nixpkgs/pull/101905

**Comment by jonringer** [comment]
Closing this issue.
