### ISSUE TITLE
What is the Entropy Estimation Based on?

### ISSUE THREAD

**Issue by xanderdunn** [nipy/nitime#182]
Thanks for providing this code as open source.

Looking at the [entropy docs](http://nipy.org/nitime/api/generated/nitime.algorithms.entropy.html) as well as the [entropy code](https://github.com/nipy/nitime/blob/master/nitime/algorithms/entropy.py#L7) I wasn't able to learn what theoretical [entropy estimation technique](https://en.wikipedia.org/wiki/Entropy_estimation) it was based on. Is there a particular technique it relates to? 

The entropy estimations don't appear to be very high resolution? Here are calculations of the the nitime entropy on 10,000 samples from a handful of continuous distributions:
```
+------------------+-----------+---------+-------------+
| distribution     | k-nearest | nitime  | nitime nats |
+------------------+-----------+---------+-------------+
| constant         | -23.0236  | 0.0000  | 0.0000      |
| line             | 7.3716    | 9.9658  | 6.9078      |
| line_more        | 9.6739    | 13.2877 | 9.2103      |
| uniform_to_e     | 0.9948    | 13.2877 | 9.2103      |
| uniform_to_count | 9.2249    | 13.2877 | 9.2103      |
| uniform_normed   | -4.0653   | 13.2877 | 9.2103      |
| uniform_fewer    | 9.2017    | 9.9658  | 6.9078      |
| normal           | -2.2410   | 13.2877 | 9.2103      |
| abs_normal       | 8.1006    | 13.2877 | 9.2103      |
| normal_normed    | -6.8273   | 13.2877 | 9.2103      |
| sine             | -0.7259   | 13.2877 | 9.2103      |
| TrigData_sin     | 4.2290    | 13.2877 | 9.2103      |
| TrigData_acosh   | 4.6336    | 13.2877 | 9.2103      |
| levy_stable      | 0.1780    | 13.2877 | 9.2103      |
| cauchy           | 6.5244    | 13.2877 | 9.2103      |
```

The first column is using the k-nearest entropy estimator from [here](https://github.com/paulbrodersen/entropy_estimators/blob/master/entropy_estimators/continuous.py#L173). Note that the [nat](https://en.wikipedia.org/wiki/Nat_(unit)) is defined as the information content of the uniform distribution on the internal [0, e]. k-nearest returns entropy in nats and indeed you can see it produces an entropy estimate of `0.9953` for the `uniform_to_e` distribution. nitime's entropy uses `log2` so it appears to be returning bits. I converted bits to nats using 1 nat = 1/ln(2) bits. You can see these values in the nitime nats column. nitime's entropy estimations are almost all the same value, and are very different from expected values. Is nitime's entropy estimator intended for a different use case?

**Comment by arokem** [comment]
Thanks for checking this so closely. To be completely honest, I am a bit fuzzy on why/how I implemented this. Looking at the tests, it looks like this was intended to work with discrete (integer) valued variables, not continuous variables. For example, spike counts. I guess that should be better documented.

**Comment by xanderdunn** [comment]
Thanks, I'll go ahead and close this. I think my use case is out of scope for nitime.
