### ISSUE TITLE
nitime not installing in Jupyter

### ISSUE THREAD

**Issue by CelienI** [nipy/nitime#186]
Hello, 

I installed nitime in general using the command window but afterwards was made aware that it has to be installed directly in Jupyter because otherwise it doesn't work there. However, when I try to install it in Jupyter (using: "! pip install nitime") , the kernel just remains busy and nothing happens (I gave it 3 hours). Weird thing is that I tried the same command to install another random package ("geocoder") en this immediately worked. 

Does anyone know why nitime won't install? 

Thanks in advance!

**Comment by arokem** [comment]
I am not sure. Do you have the dependencies for nitime already installed in the environment in which you are installing it?

**Comment by effigies** [comment]
Instinctively closed due to no response in 2+ years. Not a maintainer but weirdly have permissions. Feel free to reopen...
