### ISSUE TITLE
nitime.analysis.coherence.MTCoherenceAnalyzer causing an error when fed with bandwidth parameter

### ISSUE THREAD

**Issue by liorgolgher** [nipy/nitime#188]
Greetings,

I have noisy vascular measurements acquired at 30Hz for 89 seconds. I'd like to inspect their multi-taper coherence in the 0.1-2.5Hz range, as done in [1]. In particular, I'd like to use an increased bandwidth of 0.1Hz, trading frequency resolution in favor of reduced variance. I've followed the worked example provided in [2] with the following modifications:

```
multitaper_bandwidth = 0.1 # [Hz]
T = TimeSeries(my_signal, sampling_rate=30.02)
T.metadata['roi'] = vessel_names

C2 = MTCoherenceAnalyzer(T, bandwidth = multitaper_bandwidth)

freq_idx = np.where((C2.frequencies > 0.1) * (C2.frequencies < 2.5))[0]

coh_array[:,:,frequency_band_num] = np.max(C2.coherence[:, :, freq_idx], axis=-1)  # finding the maximal coherence in the frequency domain
```

However, when I inspect freq_idx I see that its bandwidth is always 1/89 = 0.011 Hz, regardless of the value fed to multitaper_bandwidth. Moreover, whenever I feed the bandwidth parameter I get the following TypeError:

```
Traceback (most recent call last):
  File "neurovascular_coherences.py", line 323, in <module>
    coh_array[:,:,frequency_band_num] = np.max(C2.coherence[:, :, freq_idx], axis=-1)  # finding the maximal value on the frequency dimension
  File "/.../envs/nitime/lib/python3.7/site-packages/nitime/descriptors.py", line 140, in __get__
    val = self.getter(obj)
  File "/.../envs/nitime/lib/python3.7/site-packages/nitime/analysis/coherence.py", line 348, in coherence
    (self.weights[i], self.weights[j]),
  File "/.../envs/nitime/lib/python3.7/site-packages/nitime/descriptors.py", line 140, in __get__
    val = self.getter(obj)
  File "/.../envs/nitime/lib/python3.7/site-packages/nitime/analysis/coherence.py", line 318, in weights
    w = np.empty((channel_n, self.df, self._L))
TypeError: 'float' object cannot be interpreted as an integer
```

Could you please suggest what am I doing wrong and how to resolve this error?

Many thanks,
Lior

[1] https://www.pnas.org/content/108/20/8473
[2] http://nipy.org/nitime/examples/multi_taper_coh.html

**Comment by arokem** [comment]
Thanks for reporting. Does the change in #189 make sense to you?

**Comment by liorgolgher** [comment]
Thank you very much for your prompt, helpful reply! That change resolves the said TypeError. However, C2.frequencies[freq_idx] is still unaffected by the value multitaper_bandwidth. C2.frequencies always increment by 0.011Hz, e.g. [0.10111527 0.1123503  0.12358533 0.13482036],  regardless of the value of multitaper_bandwidth, be it 0.1, 1 or 10.

I suspect that it's not an error with the code but with my usage of it. Shouldn't the bandwidth parameter of MTCoherenceAnalyzer correspond to the frequency interval widths in Hz?

Thanks from HUJI,
Lior

**Comment by liorgolgher** [comment]
ok, it turns out that the computed coherence does vary with the value of the bandwidth parameter fed to MTCoherenceAnalyzer. It is just the C2.frequencies incrementation that remains unaffected. I apologize for my misunderstanding and thank you again for your kind assistance!

Best,
Lior
