### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by effigies** [nipy/nitime#211]
@arokem Sorry to bug, but would you be able to cut a 3.12-compatible release? With or without #210, it would allow me to drop cython as a runtime dependency downstream.

**Comment by arokem** [comment]
Sure. Based on https://github.com/nipy/nitime/pull/199, IIRC that means changing the version strings in the version.py file and then pushing a tag, correct? I believe you also have all the permissions to do this (?) and should feel empowered to do so.

**Comment by effigies** [comment]
Should just mean tagging and pushing to GitHub. `_version.py` is auto-generated.
