### ISSUE TITLE
Could you provide `aarch64` wheels?

### ISSUE THREAD

**Issue by hoechenberger** [nipy/nitime#216]
Hello, I was wondering if you could kindly provide wheels for `aarch64` on PyPI? This would be Linux on ARM. It's becoming more widespread as more people are running Docker on their Apple Silicon machines.

Thank you very much!

**Comment by hoechenberger** [comment]
Friendly ping :) 



cc @larsoner

**Comment by arokem** [comment]
Hello! Sorry for the slowness. I have no objection in principle, but in practice I wouldn't know where to get started. So, if you would like to propose _how_ to do this, I am happy to include this.
